### ISSUE TITLE
How to download from folder?

### ISSUE THREAD

**Issue by spenceralbrecht** [replit/replit-object-storage-python#9]
I created a folder within my bucket but now I don't know how to access that folder specifically. 

I tried putting the folder name in the client initialization and also specifying the full path in the `downloadAsBytes` function but neither worked.

![CleanShot 2024-05-29 at 14 28 43@2x](https://github.com/replit/replit-object-storage-python/assets/15025912/dae75ac5-c15e-46a6-a64e-de36f883f86c)

**Comment by blast-hardcheese** [comment]
Hey @spenceralbrecht! Please pardon the delay, hopefully you were able to figure it out! If not, can you share an example of what you're trying to do?

This may have been an issue with an earlier version of the library -- trying to replicate what you shared in the initial issue, you can see I've uploaded a `png` and am using `download_as_bytes`:

![image](https://github.com/user-attachments/assets/83d6d3bd-e267-4205-b155-57cc93262d41)

If this is still an issue, please feel free to reopen or comment.
